#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# sudo not required for some system commands
for command in poweroff reboot tlmgr; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
    gd="pushd" \
    pd="popd"

# Colorize commands when possible.
alias \
	ls="ls --color=auto" \
    ll="ls -l" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \

# system-utility style
alias \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME}/shell/shortcutrc ; 
        source ${XDG_CONFIG_HOME}/shell/zshnameddirrc ; 
        source ${XDG_CONFIG_HOME}/shell/functions" \

# dotfiles management
alias \
	dotf="git --git-dir=$HOME/.dotf-cfg/ --work-tree=$HOME" \
    dotfs="dotf status -s" \
    dotfa="dotf add -u" \
    dotfc="dotf commit -m" \
    dotfp="dotf push"

# git management
alias \
	g="git" \
    gs="git status -s" \
    ga="git add -A" \
    gc="git commit -m" \

# programs
alias \
    yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarnrc"
    bms="bkmr search --fzf" \
	ffmpeg="ffmpeg -hide_banner" \
    abook="abook --config $XDG_DATA_HOME/abook/abookrc --datafile $XDG_DATA_HOME/abook/addressbook" \
    abudget="${HOME}/.local/scripts/apps/actual_budget_start" \
    neomutt="TERM=xterm-direct neomutt" \
    yabspace="yabai -m space --create" \
    yt="yt-dlp --embed-metadata -i" \
    yta="yt-dlp -x -f bestaudio/best"
