#! /usr/bin/env bash

list=$1

read -p 'Give alternate sequential file naming? (Y/N) ' choice
if [[ $choice == [yY] ]]; then
	read -p 'Alternate name (will be appended with sequential numbering) ' alt_file_name
else
	echo 'no alternate file name'
fi

read -p 'Are the files in the list audio or video? (A/V): ' choice
if [[ $choice == [aA] ]]; then
	yt-dlp -x -f bestaudio/best -a $list -o "${alt_file_name}-%(autonumber)02d.%(ext)s"
elif [[ $choice == [vV] ]]; then
	yt-dlp --embed-metadata -i -a $list -o "${alt_file_name}-%(autonumber)02d.%(ext)s"
else
	echo 'aborted'
fi
