[profiles.user]
user_id = "@tjex:envs.net"

[settings]
username_display = "localpart"
default_room = "lounge"

[dirs]
cache = "/Users/tjex/.cache/iamb"
data = "/Users/tjex/.local/share/iamb"

[layout]
style = "new"

[settings.sort]
members = ["power"]

[macros.insert]
"kj" = "<Esc>"

[macros.normal]
"V" = "<C-w>m"
"<C-r>" = ":rooms<CR>"
