#!/usr/bin/env bash

# backup selected files and folders to cairo usb thumb drive

script_dir=$(dirname "$(realpath "$0")")

# only run if cairo is mounted
if  mount | grep "cairo" > /dev/null ; then
    # docs
    rsync -arplu --del ~/docs /Volumes/backups-cairo ; echo "copied: docs"
    rsync -arplu --del ~/notes /Volumes/backups-cairo ; echo "copied: notes"
    rsync -arplu --del ~/lists /Volumes/backups-cairo ; echo "copied: lists"
    rsync -arplu --del --exclude="massage" ~/obsidian /Volumes/backups-cairo ; echo "copied: obsidian"
    
    # system / program relevant
    rsync -arplu --del ${PASSWORD_STORE_DIR} /Volumes/backups-cairo ; echo "copied: password store"
    rsync -arplu --del ~/.local/src/abudget/actual-tjex/user-files/* /Volumes/backups-cairo/abudget-user-files ; echo "copied: abudgt user files"
    rsync -arplu --del ~/.ssh/* /Volumes/backups-cairo/keys/ssh ; echo "backup: ssh"

    # list of individual files to copy (little backups)
    # /Users/tjex is the root folder for execution, i.e. the path that rsync will prepend to paths in the list
    rsync -av --del --files-from="/Users/tjex/.local/scripts/sys-admin/indiv-files.txt" /Users/tjex/ /Volumes/backups-cairo/tjex ; echo "copied individual files from list"

    # Export Brewfile
    echo "========== RSYNC COMPLETED =========="

    cd /Volumes/backups-cairo 
 
    # rm Brewfile if it is present
    if [ -f Brewfile ] ; then
        echo "Brewfile found, removing it"
        rm Brewfile
    fi

    # DEV ENV #
    # ####### #

    # generate new Brewfile
    echo "exporting Brewfile"
    brew bundle dump ; cd ${script_dir}

    # sys python venv
    pip freeze > /Volumes/backups-cairo/sys_venv_requirements.txt

else
    echo "cairo not mounted"
fi


