#!/usr/bin/env bash

cairo="/Volumes/cairo"
restic=$(which restic)

if  mount | grep "$cairo" > /dev/null ; then
    restic -r "$cairo"/backups/r-docs backup \
        --tag script-bup $HOME/docs \
        --password=${RESTICPASS}
    echo "Backed up docs to cairo"
    restic -r "$cairo"/backups/r-ssh backup \
        --tag script-bup $HOME/.ssh \
        --password=${RESTICPASS}
    echo "Backed up ssh to cairo"
    restic -r "$cairo"/backups/r-gnupg backup \
        --tag script-bup $XDG_DATA_HOME/gnupg \
        --password=${RESTICPASS}
    echo "Backed up gnupg to cairo"
fi
