#! /usr/bin/env bash

func() {
    read -p "test " test
    echo ${test}
}

whichgo() {
    if $(which go) == "" ; then
        echo "yes"
    else
        echo "no"
        echo $(which go)
    fi
}

whichgo
