#!/usr/bin/env zsh

SHA256=$(shasum -a 256 $(which yabai) | awk "{print \$1;}")
if [ -f "/private/etc/sudoers.d/yabai" ]; then
    sudo sed -i '' -e 's/sha256:[[:alnum:]]*/sha256:'${SHA256}'/' /private/etc/sudoers.d/yabai
    echo "sudoers > yabai > sha256 hash update complete"
else
    echo "Sudoers file does not exist yet, or could not be found." 
    echo "Please create one before running this script."
fi
